import * as Dialog from '@radix-ui/react-dialog';
import {
  VF_LIMITS,
  VF_MARKETS,
  VF_RETURN_PERCENT,
  VF_RULES_DIGEST,
  VF_RULES_ID,
  VF_TIMING,
} from '@socialplay/shared';
import { formatCredits, formatOdds } from '@/lib/football/format';

const seconds = (ms: number) => `${ms / 1000} s`;

export function RulesDialog() {
  return (
    <Dialog.Root>
      <Dialog.Trigger className="vf-help">How it works ↗</Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className="vf-overlay" />
        <Dialog.Content className="vf-dialog vf-dialog--rules" aria-describedby="vf-rules-desc">
          <Dialog.Title>PlayQube Virtual Football 3D: rules</Dialog.Title>
          <Dialog.Description id="vf-rules-desc">
            An original simulated league using free, non-redeemable practice credits. It is not
            connected to any real club, league or competition.
          </Dialog.Description>
          <h3>The league</h3>
          <p>
            Twenty fictional PlayQube clubs play a fixed double round-robin: 38 matchweeks of{' '}
            {VF_TIMING.fixturesPerWeek} matches per season, and every club meets every other club
            home and away. A new matchweek starts every five minutes.
          </p>
          <ol>
            <li>Selections are open for {seconds(VF_TIMING.selectionMs)}.</li>
            <li>
              First half {seconds(VF_TIMING.firstHalfMs)}, half-time {seconds(VF_TIMING.halftimeMs)}
              , second half {seconds(VF_TIMING.secondHalfMs)}: a 90-minute match compressed to{' '}
              {seconds(VF_TIMING.matchMs)}.
            </li>
            <li>
              Results and the table stay on screen for {seconds(VF_TIMING.resultsMs)} before the
              next matchweek opens.
            </li>
          </ol>
          <p>
            A matchweek is created during its selection window while this practice league is
            running. Missed matchweeks are shown as not played; their results are never made up
            afterwards.
          </p>
          <h3>Tickets</h3>
          <ul>
            <li>
              A ticket holds up to {VF_LIMITS.maxLines} lines: singles, and multiples of{' '}
              {VF_LIMITS.minLegsPerMultiple} to {VF_LIMITS.maxLegsPerMultiple} selections from
              different matches, every one of which must win.
            </li>
            <li>
              Stake {VF_LIMITS.minLineStake}–{VF_LIMITS.maxLineStake} credits per line, up to{' '}
              {formatCredits(VF_LIMITS.maxTicketStake)} per ticket and{' '}
              {VF_LIMITS.maxTicketsPerMatchweek} tickets per matchweek.
            </li>
            <li>
              Combined odds are capped at {formatOdds(VF_LIMITS.maxCombinedOddsCents)}×, a line
              returns at most {formatCredits(VF_LIMITS.maxLineReturn)} credits and a ticket at most{' '}
              {formatCredits(VF_LIMITS.maxTicketReturn)}.
            </li>
            <li>
              A winning line returns stake × the product of its prices, rounded down once to a whole
              credit. A losing line returns 0.
            </li>
            <li>
              Confirmed tickets cannot be changed, cancelled or cashed out. There is no autoplay and
              no jackpot.
            </li>
            <li>
              Pressing confirm twice, or retrying after a lost connection, can never charge you
              twice: each confirmation has a receipt key, and the same ticket always returns the
              same receipt.
            </li>
          </ul>
          <h3>How results and prices are made</h3>
          <p>
            Each match is generated by the server from a secret seed that is committed (hashed)
            before selections open and revealed after the matchweek. The same finite model produces
            both the result and the prices: a score with six goals or fewer, with goal times in
            order. After full time you can verify every result in your browser.
          </p>
          <p>
            Prices are fixed when the matchweek opens and never move. Each is {VF_RETURN_PERCENT}%
            of the fair price implied by the model&apos;s probability, rounded down to the
            hundredth, so every market returns about {VF_RETURN_PERCENT}% on average. A selection
            whose price would fall below {formatOdds(VF_LIMITS.minOddsCents)} or above{' '}
            {formatOdds(VF_LIMITS.maxOddsCents)} is shown as not offered. Club strength is public,
            but results are random: form and previous matches do not predict the next one.
          </p>
          <p>
            The 3D match is a decorative replay of goals the server has already released.
            Players&apos; movement between goals is illustrative and never affects any result or
            price.
          </p>
          <h3>Markets</h3>
          <dl className="vf-rules-markets">
            {VF_MARKETS.map((m) => (
              <div key={m.key}>
                <dt>{m.title}</dt>
                <dd>{m.rule}</dd>
              </div>
            ))}
          </dl>
          <p className="vf-fine">
            Rules {VF_RULES_ID} · digest {VF_RULES_DIGEST.slice(0, 16)}… Practice credits are free,
            cannot be bought, transferred or redeemed, and have no connection to Coins or any cash
            value.
          </p>
          <Dialog.Close className="vf-secondary">Close rules</Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
